# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u4f1a\u8bae\u5ba4')),
                ('num', models.IntegerField(default=0, verbose_name='\u5bb9\u7eb3\u4eba\u6570')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
                ('add_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'room_info',
                'verbose_name': '\u8f66\u8f86\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserMeetRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resign', models.CharField(max_length=2000, verbose_name='\u539f\u56e0')),
                ('peo_num', models.IntegerField(default=0, verbose_name='\u4eba\u6570')),
                ('shenpi_id', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=5000, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('yijian', models.CharField(default='', max_length=200, verbose_name='\u610f\u89c1')),
                ('begain_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('add_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.MeetingRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_room_detail',
                'verbose_name': '\u7528\u8f66\u8868',
            },
        ),
    ]
