# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='user',
            name='depart',
            field=models.CharField(default='', max_length=50, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='\u8d26\u53f7\u72b6\u6001'),
        ),
    ]
