# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_log', '0002_auto_20180111_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='d_id',
            field=models.ImageField(default=0, upload_to=b'', verbose_name='\u90e8\u95e8id'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.IntegerField(default=0, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='p_id',
            field=models.ImageField(default=0, upload_to=b'', verbose_name='\u804c\u4f4did'),
        ),
    ]
